version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: infomate_db
    environment:
      POSTGRES_USER: infomate
      POSTGRES_PASSWORD: infomate123
      POSTGRES_DB: infomate_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
